### ISSUE TITLE
FE: feature extractors

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#51]
This is an umbrella issue for [Feature Extractors (FE)](https://docs.google.com/document/d/1cInzLuz-qygwrTvddGIbzBnzF4nnsAuk_24a6Nhff0k/edit#heading=h.vjihr4gw6m8r) implementation:

 - [x] Define gRPC Service, messages in `src/main/proto/*.proto` https://github.com/src-d/gemini/pull/52
 - [x] Generation scripts: server in `python src/main/python/generated.py`,  #57 
    Python CLI app `src/main/python/main.py` configures the port
 - [x] Generation scripts: client in scala `src/main/scala` #63 
 - [x] Docker file \w feature extractor (used on CI) #73 
 - [x] Implement FE service: call `sourced.ml.extractros` #73 
 - [x] Add missed weight parameter to extractors #79
 - [x] Integration Tests: add CI profile, that for a given UAST checks the response is not failing #81

**Comment by smacker** [comment]
everything is implemented! 🎉 
I'm closing the issue. If we would need any further improvements later, we will address them in separate issues.
