### ISSUE TITLE
Query: add similar files

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#53]
Umbrella issue to update current implementation to use a :similarity" notion from Apollo:

 - [x] UAST extraction https://github.com/src-d/gemini/issues/68
 - [x] talk to FE gRPC, to extract features https://github.com/src-d/gemini/issues/69
 - [x] Find/write CPU WMH implementation in Scala (tests!) https://github.com/src-d/gemini/pull/78
 - [x] Write `query.py#query()` logic on Scala side https://github.com/src-d/gemini/pull/89
 - [x] Update `./query` CLI output to include similar files #92 
 - [x] Integration test with all components (except hash, use cql fixture for it)

**Comment by bzz** [comment]
@smacker thank you for keeping the scope of work in issue description up to date! 👍

**Comment by bzz** [comment]
@smacker could you please take a look and update PR description, add things that we might have left for this ☂️ ? Thanks!

**Comment by smacker** [comment]
looks like everything is done here. I have checked checkboxes in description and I'm closing the issue.
Feel free to create a new one if we need further improvements of query.
