### ISSUE TITLE
Report: add similar files

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#54]
Umbrella issue for updating current implementation to use ["similarity" from Apollo](https://docs.google.com/document/d/1cInzLuz-qygwrTvddGIbzBnzF4nnsAuk_24a6Nhff0k/edit#heading=h.f29zztcqkssd):

 - [x] Query DB, detect connected components, write Parquet in Scala https://github.com/src-d/gemini/issues/58
 - [x] Internal library in python (function/class) for community detection \w [IGraph](https://github.com/igraph/igraph)  https://github.com/src-d/gemini/pull/85
 - [x] App in Python, reading Parquet, doing community detection using the library above and printing the output #60
